"""Configuration management.

Public API:
    - ``Settings``: Root config aggregating all YAML configs + env vars.
    - ``EnvConfig``: Environment variables loaded from ``.env``.
    - ``load_config()``: Load and validate all YAML configs.
    - ``get_default_config()``: Get default config (no YAML files required).

All config classes are re-exported here for convenient access via
``from energy_forecast.config import <ClassName>``.
"""

# -- general (helpers, project, pipeline, data-loader, openmeteo) -----------
# -- loader (root Settings, load functions) ---------------------------------
from energy_forecast.config._loader import (
    _DEFAULT_REGION,
    Settings,
    get_default_config,
    load_config,
)

# -- api (env, database, monitoring, API serving) ---------------------------
from energy_forecast.config.api import (
    ApiConfig,
    ApiEmailConfig,
    ApiFilesConfig,
    DatabaseConfig,
    DriftDetectionConfig,
    EnvConfig,
    MonitoringConfig,
)

# -- features (calendar, consumption, weather, solar, EPIAS) ----------------
from energy_forecast.config.features import (
    AnticipationConfig,
    BusinessHoursConfig,
    CalendarConfig,
    ComfortIndexConfig,
    ConsumptionConfig,
    ConsumptionLagConfig,
    CyclicalPeriod,
    EpiasConfig,
    EpiasExpandingConfig,
    EpiasLagConfig,
    EpiasRollingConfig,
    EpiasSourceConfig,
    EwmaConfig,
    ExpandingConfig,
    ExtremeFlagsConfig,
    FeaturesConfig,
    GenerationCompositesConfig,
    GenerationConfig,
    GenerationExpandingConfig,
    GenerationLagConfig,
    GenerationRollingConfig,
    HeatIndexConfig,
    HolidaysConfig,
    MomentumConfig,
    QuadraticTemperatureConfig,
    QuantileConfig,
    RollingConfig,
    SolarConfig,
    SolarLagRangeConfig,
    SolarLeadConfig,
    SolarLocationConfig,
    SolarPanelConfig,
    SplineSeasonalityConfig,
    TargetEncodingConfig,
    TempDeviationConfig,
    TrendRatioConfig,
    TrendRatioPairConfig,
    WeatherFeaturesConfig,
    WeatherInteractionsConfig,
    WeatherLagsConfig,
    WeatherRollingConfig,
    WeatherSeverityConfig,
    WeatherThresholdsConfig,
)
from energy_forecast.config.general import (
    CityConfig,
    DataLoaderConfig,
    DataValidationConfig,
    EpiasApiConfig,
    ExcelColumnsConfig,
    ForecastConfig,
    GeocodingConfig,
    LoggingConfig,
    OpenMeteoApiConfig,
    OpenMeteoConfig,
    PathsConfig,
    PipelineConfig,
    ProjectConfig,
    RegionConfig,
    TrainingPathsConfig,
    WeatherCacheConfig,
    _load_yaml,
)

# -- models (catboost, prophet, tft, ensemble, hyperparameters) -------------
from energy_forecast.config.models import (
    CatBoostConfig,
    CatBoostNanHandling,
    CatBoostTrainingConfig,
    CrossValidationConfig,
    EnsembleConfig,
    EnsembleFallbackConfig,
    EnsembleOptimizationConfig,
    EnsembleWeightBoundsConfig,
    EnsembleWeightsConfig,
    HyperparameterConfig,
    ModelSearchConfig,
    ProphetChangepointConfig,
    ProphetConfig,
    ProphetHolidaysConfig,
    ProphetOptimizationConfig,
    ProphetRegressorConfig,
    ProphetSeasonalityConfig,
    ProphetUncertaintyConfig,
    SearchParamConfig,
    SeasonalityPeriodConfig,
    StackingConfig,
    StackingMetaLearnerConfig,
    TFTArchitectureConfig,
    TFTConfig,
    TFTCovariatesConfig,
    TFTOptimizationConfig,
    TFTTrainingConfig,
    TSMixerxArchitectureConfig,
    TSMixerxConfig,
    TSMixerxCovariatesConfig,
    TSMixerxOptimizationConfig,
    TSMixerxTrainingConfig,
)

__all__ = [
    # _loader
    "_DEFAULT_REGION",
    # features
    "AnticipationConfig",
    # api
    "ApiConfig",
    "ApiEmailConfig",
    "ApiFilesConfig",
    "BusinessHoursConfig",
    "CalendarConfig",
    # models
    "CatBoostConfig",
    "CatBoostNanHandling",
    "CatBoostTrainingConfig",
    # general
    "CityConfig",
    "ComfortIndexConfig",
    "ConsumptionConfig",
    "ConsumptionLagConfig",
    "CrossValidationConfig",
    "CyclicalPeriod",
    "DataLoaderConfig",
    "DataValidationConfig",
    "DatabaseConfig",
    "DriftDetectionConfig",
    "EnsembleConfig",
    "EnsembleFallbackConfig",
    "EnsembleOptimizationConfig",
    "EnsembleWeightBoundsConfig",
    "EnsembleWeightsConfig",
    "EnvConfig",
    "EpiasApiConfig",
    "EpiasConfig",
    "EpiasExpandingConfig",
    "EpiasLagConfig",
    "EpiasRollingConfig",
    "EpiasSourceConfig",
    "EwmaConfig",
    "ExcelColumnsConfig",
    "ExpandingConfig",
    "ExtremeFlagsConfig",
    "FeaturesConfig",
    "ForecastConfig",
    "GenerationCompositesConfig",
    "GenerationConfig",
    "GenerationExpandingConfig",
    "GenerationLagConfig",
    "GenerationRollingConfig",
    "GeocodingConfig",
    "HeatIndexConfig",
    "HolidaysConfig",
    "HyperparameterConfig",
    "LoggingConfig",
    "ModelSearchConfig",
    "MomentumConfig",
    "MonitoringConfig",
    "OpenMeteoApiConfig",
    "OpenMeteoConfig",
    "PathsConfig",
    "PipelineConfig",
    "ProjectConfig",
    "ProphetChangepointConfig",
    "ProphetConfig",
    "ProphetHolidaysConfig",
    "ProphetOptimizationConfig",
    "ProphetRegressorConfig",
    "ProphetSeasonalityConfig",
    "ProphetUncertaintyConfig",
    "QuadraticTemperatureConfig",
    "QuantileConfig",
    "RegionConfig",
    "RollingConfig",
    "SearchParamConfig",
    "SeasonalityPeriodConfig",
    "Settings",
    "SolarConfig",
    "SolarLagRangeConfig",
    "SolarLeadConfig",
    "SolarLocationConfig",
    "SolarPanelConfig",
    "SplineSeasonalityConfig",
    "StackingConfig",
    "StackingMetaLearnerConfig",
    "TFTArchitectureConfig",
    "TFTConfig",
    "TFTCovariatesConfig",
    "TFTOptimizationConfig",
    "TFTTrainingConfig",
    "TSMixerxArchitectureConfig",
    "TSMixerxConfig",
    "TSMixerxCovariatesConfig",
    "TSMixerxOptimizationConfig",
    "TSMixerxTrainingConfig",
    "TargetEncodingConfig",
    "TempDeviationConfig",
    "TrainingPathsConfig",
    "TrendRatioConfig",
    "TrendRatioPairConfig",
    "WeatherCacheConfig",
    "WeatherFeaturesConfig",
    "WeatherInteractionsConfig",
    "WeatherLagsConfig",
    "WeatherRollingConfig",
    "WeatherSeverityConfig",
    "WeatherThresholdsConfig",
    "_load_yaml",
    "get_default_config",
    "load_config",
]
